version: '3.8'

services:
  postgres:
    container_name: cardapio-digital
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cardapio-digital
      PGDATA: /var/lib/postgresql/data/postgres
    volumes:
      - ./data/pg:/var/lib/postgresql/data/postgres
